name: dart_bolt12_decoder
description: Decoder utility for BOLT 12 offers, request and invoices in Dart.
version: 0.8.0
repository: https://github.com/anasfik/dart_bolt12_decoder
homepage: https://gwhyyy.com
topics: [bolt 12, lightning, bitcoin, decoder, offers]

environment:
  sdk: ^3.4.1


dependencies:
  crypto: ^3.0.3
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
